### ISSUE TITLE
Office 365 calender synchronization fails

### ISSUE THREAD

**Issue by mortenss** [exo-addons/exchange-extension#1]
We are running latest version of addon and using Office 365, but when configurering exo exchange extionsion to connect to https://outlook.office365.com/EWS/Exchange.asmx and in the WebInterface configures calender with username, password it connects just fine but calender is never synchronized.

We get this errors in the log:

2015-03-25 10:46:43,682 | ERROR | Error while synchronizing calndar entries. [o.e.e.e.listener.IntegrationListener<pool-2-thread-4>]
microsoft.exchange.webservices.data.ServiceRequestException: The request failed. Could not read value from START_ELEMENT.Could not find CHARACTERS
        at microsoft.exchange.webservices.data.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:62) ~[exchange-ws-api.jar:na]
        at microsoft.exchange.webservices.data.MultiResponseServiceRequest.execute(MultiResponseServiceRequest.java:142) ~[exchange-ws-api.jar:na]
        at microsoft.exchange.webservices.data.ExchangeService.findItems(ExchangeService.java:928) ~[exchange-ws-api.jar:na]
        at microsoft.exchange.webservices.data.ExchangeService.findItems(ExchangeService.java:1006) ~[exchange-ws-api.jar:na]
        at org.exoplatform.extension.exchange.service.IntegrationService.searchAllItems(IntegrationService.java:765) ~[exchange-extension-service.jar:1.0.2]
        at org.exoplatform.extension.exchange.service.IntegrationService.synchronizeFullCalendar(IntegrationService.java:123) ~[exchange-extension-service.jar:1.0.2]
        at org.exoplatform.extension.exchange.listener.IntegrationListener$ExchangeIntegrationTask.synchronizeByModificationDate(IntegrationListener.java:394) ~[exchange-extension-service.jar:1.0.2]
        at org.exoplatform.extension.exchange.listener.IntegrationListener$ExchangeIntegrationTask.run(IntegrationListener.java:334) ~[exchange-extension-service.jar:1.0.2]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:1.7.0_75]
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source) ~[na:1.7.0_75]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [na:1.7.0_75]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.7.0_75]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.7.0_75]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.7.0_75]
        at java.lang.Thread.run(Unknown Source) [na:1.7.0_75]
Caused by: microsoft.exchange.webservices.data.ServiceXmlDeserializationException: Could not read value from START_ELEMENT.Could not find CHARACTERS
        at microsoft.exchange.webservices.data.EwsXmlReader.readValue(EwsXmlReader.java:467) ~[exchange-ws-api.jar:na]
        at microsoft.exchange.webservices.data.EwsXmlReader.readElementValue(EwsXmlReader.java:352) ~[exchange-ws-api.jar:na]
        at microsoft.exchange.webservices.data.TypedPropertyDefinition.loadPropertyValueFromXml(TypedPropertyDefinition.java:127) ~[exchange-ws-api.jar:na]
        at microsoft.exchange.webservices.data.PropertyBag.loadFromXml(PropertyBag.java:487) ~[exchange-ws-api.jar:na]
        at microsoft.exchange.webservices.data.ServiceObject.loadFromXml(ServiceObject.java:270) ~[exchange-ws-api.jar:na]
        at microsoft.exchange.webservices.data.FindItemResponse.internalReadItemsFromXml(FindItemResponse.java:161) ~[exchange-ws-api.jar:na]
        at microsoft.exchange.webservices.data.FindItemResponse.readElementsFromXml(FindItemResponse.java:83) ~[exchange-ws-api.jar:na]
        at microsoft.exchange.webservices.data.ServiceResponse.loadFromXml(ServiceResponse.java:102) ~[exchange-ws-api.jar:na]
        at microsoft.exchange.webservices.data.MultiResponseServiceRequest.parseResponse(MultiResponseServiceRequest.java:54) ~[exchange-ws-api.jar:na]
        at microsoft.exchange.webservices.data.ServiceRequestBase.readResponse(ServiceRequestBase.java:532) ~[exchange-ws-api.jar:na]
        at microsoft.exchange.webservices.data.SimpleServiceRequestBase.readResponse(SimpleServiceRequestBase.java:176) ~[exchange-ws-api.jar:na]
        at microsoft.exchange.webservices.data.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:49) ~[exchange-ws-api.jar:na]
        ... 14 common frames omitted

Hope you can assist in getting this to work.

Thanks,
Morten

**Comment by boubaker** [comment]
I have changed the version of EWS API, can you test the last master version?

**Comment by mortenss** [comment]
Hi and thanks for quick action. Have forwarded your email to my colleague to test. Get back to you soon with result. Have a great day. Best Regards Morten

Sendt fra min Samsung-enhed

-------- Oprindelig meddelelse --------
Fra: Boubaker Khanfir notifications@github.com
Dato: 27/03/2015 11.01 (GMT+01:00)
Til: exo-addons/exchange-extension exchange-extension@noreply.github.com
Cc: Morten Steen Søndergaard morten@itx.dk
Emne: Re: [exchange-extension] Office 365 calender synchronization fails (#1)

I have changed the version of EWS API, can you test the last master version?

##
