### ISSUE TITLE
Error while synchronizing calndar entries (v1.1.0 and PLF 4.2.0)

### ISSUE THREAD

**Issue by majaode** [exo-addons/exchange-extension#4]
Error after install exo-exchange-extension v1.1.0 (Platform 4.2.0)

```
2015-11-18 11:19:20,449 | WARN  | Inconsistent data delivered by MS Exchange. The recurrent Event has end but end date is null: 'CS Biweekly', start:Fri Nov 27 00:00:00 ICT 2015, end : Fri Nov 27 09:30:00 ICT 2015 [o.e.e.exchange.service.ExoStorageService<pool-2-thread-4>] 
2015-11-18 11:19:23,731 | WARN  | Inconsistent data delivered by MS Exchange. The recurrent Event has end but end date is null: 'CS Meeting New Schedule', start:Fri Dec 04 00:00:00 ICT 2015, end : Fri Dec 04 09:30:00 ICT 2015 [o.e.e.exchange.service.ExoStorageService<pool-2-thread-4>] 
2015-11-18 11:19:44,658 | ERROR | Error while synchronizing calndar entries. [o.e.e.e.listener.IntegrationListener<pool-2-thread-7>] 
microsoft.exchange.webservices.data.ServiceResponseException: At least one recipient isn't valid.
    at microsoft.exchange.webservices.data.ServiceResponse.internalThrowIfNecessary(ServiceResponse.java:266) ~[exchange-ws-api.jar:na]
    at microsoft.exchange.webservices.data.ServiceResponse.throwIfNecessary(ServiceResponse.java:254) ~[exchange-ws-api.jar:na]
    at microsoft.exchange.webservices.data.MultiResponseServiceRequest.execute(MultiResponseServiceRequest.java:152) ~[exchange-ws-api.jar:na]
    at microsoft.exchange.webservices.data.ExchangeService.internalUpdateItems(ExchangeService.java:576) ~[exchange-ws-api.jar:na]
    at microsoft.exchange.webservices.data.ExchangeService.updateItem(ExchangeService.java:663) ~[exchange-ws-api.jar:na]
    at microsoft.exchange.webservices.data.Item.internalUpdate(Item.java:255) ~[exchange-ws-api.jar:na]
    at microsoft.exchange.webservices.data.Item.update(Item.java:388) ~[exchange-ws-api.jar:na]
    at org.exoplatform.extension.exchange.service.ExchangeStorageService.updateOrCreateExchangeAppointment(ExchangeStorageService.java:202) ~[exchange-extension-service.jar:1.1.0]
    at org.exoplatform.extension.exchange.service.ExchangeStorageService.updateOrCreateExchangeAppointment(ExchangeStorageService.java:88) ~[exchange-extension-service.jar:1.1.0]
    at org.exoplatform.extension.exchange.service.IntegrationService.synchronizeExoEventsByModificationDate(IntegrationService.java:718) ~[exchange-extension-service.jar:1.1.0]
    at org.exoplatform.extension.exchange.service.IntegrationService.synchronizeModificationsOfCalendar(IntegrationService.java:168) ~[exchange-extension-service.jar:1.1.0]
    at org.exoplatform.extension.exchange.listener.IntegrationListener$ExchangeIntegrationTask.synchronizeByModificationDate(IntegrationListener.java:462) ~[exchange-extension-service.jar:1.1.0]
    at org.exoplatform.extension.exchange.listener.IntegrationListener$ExchangeIntegrationTask.run(IntegrationListener.java:398) ~[exchange-extension-service.jar:1.1.0]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_40]
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[na:1.8.0_40]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_40]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_40]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_40]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_40]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40]
2015-11-18 11:21:12,133 | INFO  | No user session provider was available, trying to use a system session provider [o.e.calendar.service.impl.JCRDataStorage<pool-2-thread-4>] 
2015-11-18 11:21:12,149 | INFO  | No user session provider was available, trying to use a system session provider [o.e.calendar.service.impl.JCRDataStorage<pool-2-thread-4>] 
2015-11-18 11:21:12,149 | INFO  | No user session provider was available, trying to use a system session provider [o.e.calendar.service.impl.JCRDataStorage<pool-2-thread-4>] 
2015-11-18 11:21:12,149 | INFO  | No user session provider was available, trying to use a system session provider [o.e.calendar.service.impl.JCRDataStorage<pool-2-thread-4>] 
```

**Comment by boubaker** [comment]
This is similar to : 
- https://social.msdn.microsoft.com/Forums/azure/en-US/29fb334f-69ea-4997-a23b-c9e55ac8a17b/ews-managed-api-update-appointment-at-least-one-recipient-isnt-valid-during-update-item-with
- http://stackoverflow.com/questions/30162357/exchange-error-on-calendar-item-update-at-least-one-recipient-isnt-valid

It depends on configuration of MS Exchange. I will try to handle this exception by applying the  described workaround.

**Comment by boubaker** [comment]
You can test the workaround from here:
https://repository.exoplatform.org/content/groups/public/org/exoplatform/addons/exchange/exchange-extension-configuration-packaging/1.1.x-SNAPSHOT/exchange-extension-configuration-packaging-1.1.x-20151118.105946-6.zip
